name: publish-binary-pypi

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Validate release version
      run: |
        version=$(grep '__version__' src/reg2es/__about__.py | awk -F '"' '{print $2}')
        test "v$version" = "$GITHUB_REF_NAME"

    - name: Run tests
      run: uv run pytest

    - name: Build and publish
      run: |
        uv build
        uv publish --token ${{secrets.PYPI_TOKEN}}
